apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: mciroservice-project
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: algabrizaid/maven-opa-docker-agent:latest-44
        ports:
          - containerPort: 8080
        env:

          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-cm
                key: hostname
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
  namespace: mciroservice-project

spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: spring-boot-app


